# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\droxl\Documents\EPFL\MA2\SHS\values.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):

    def setupUi(self, MainWindow, critList):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 825)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\droxl\\Documents\\EPFL\\MA2\\SHS\\node_style.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(530, 0, 111, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.doubleSpinBox = []
        self.doubleSpinBox2 = []
        self.doubleSpinBox3 = []


        self.nb_column = 1

        for i, (min, max) in critList.items():
            self.doubleSpinBox.append(QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget))
            self.doubleSpinBox[-1].setMinimum(min)
            self.doubleSpinBox[-1].setMaximum(max)
            self.doubleSpinBox[-1].setObjectName("doubleSpinBox_"+i)
            self.verticalLayout.addWidget(self.doubleSpinBox[-1])
        
        self.nb_column = self.nb_column + 1

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(650, 0, 111, 631))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")


        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(770, 0, 111, 631))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")


        self.New = QtWidgets.QPushButton(self.centralwidget)
        self.New.setGeometry(QtCore.QRect(580, 660, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.New.setFont(font)
        self.New.setObjectName("New")
        self.New.clicked.connect(self.new_column)

        self.Copy = QtWidgets.QPushButton(self.centralwidget)
        self.Copy.setGeometry(QtCore.QRect(670, 660, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Copy.setFont(font)
        self.Copy.setObjectName("Copy")
        self.Copy.clicked.connect(self.copy)

        self.Redo = QtWidgets.QPushButton(self.centralwidget)
        self.Redo.setGeometry(QtCore.QRect(760, 660, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Redo.setFont(font)
        self.Redo.setObjectName("Reset")
        self.Redo.clicked.connect(self.reset)

        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setGeometry(QtCore.QRect(530, 740, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Next.setFont(font)
        self.Next.setIconSize(QtCore.QSize(56, 56))
        self.Next.setCheckable(True)
        self.Next.setObjectName("Next")
        self.Next.clicked.connect(self.next_page)

        self.Previous = QtWidgets.QPushButton(self.centralwidget)
        self.Previous.setGeometry(QtCore.QRect(400, 740, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Previous.setFont(font)
        self.Previous.setIconSize(QtCore.QSize(56, 56))
        self.Previous.setCheckable(True)
        self.Previous.setObjectName("Previous")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 22))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Next.setText(_translate("MainWindow", "Next"))
        self.Previous.setText(_translate("MainWindow", "Previous"))
        self.New.setText(_translate("MainWindow", "New"))
        self.Copy.setText(_translate("MainWindow", "Copy"))
        self.Redo.setText(_translate("MainWindow", "Redo"))


    def new_column(self):

        if(self.nb_column == 2):
    
            for i, (min, max) in critList.items():
                self.doubleSpinBox2.append(QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2))
                self.doubleSpinBox2[-1].setMinimum(min)
                self.doubleSpinBox2[-1].setMaximum(max)
                self.doubleSpinBox2[-1].setObjectName("doubleSpinBox2_"+i)
                self.verticalLayout_2.addWidget(self.doubleSpinBox2[-1])
            self.nb_column = self.nb_column + 1
            return
        
        if(self.nb_column == 3): 

            for i, (min, max) in critList.items():
                self.doubleSpinBox3.append(QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3))
                self.doubleSpinBox3[-1].setMinimum(min)
                self.doubleSpinBox3[-1].setMaximum(max)
                self.doubleSpinBox3[-1].setObjectName("doubleSpinBox3_"+i)
                self.verticalLayout_3.addWidget(self.doubleSpinBox3[-1])
            self.nb_column = self.nb_column + 1
            return 

    def copy(self):
        
        if(self.nb_column == 2):
    
            for i, (crit, (min, max)) in enumerate(critList.items()):
                self.doubleSpinBox2.append(QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2))
                self.doubleSpinBox2[-1].setMinimum(min)
                self.doubleSpinBox2[-1].setMaximum(max)
                self.doubleSpinBox2[-1].setObjectName("doubleSpinBox2_"+crit)
                self.verticalLayout_2.addWidget(self.doubleSpinBox2[-1])
                self.doubleSpinBox2[-1].setValue(self.doubleSpinBox[i].value())

            self.nb_column = self.nb_column + 1
            return
        
        if(self.nb_column == 3): 

            for i, (crit, (min, max)) in enumerate(critList.items()):
                self.doubleSpinBox3.append(QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3))
                self.doubleSpinBox3[-1].setMinimum(min)
                self.doubleSpinBox3[-1].setMaximum(max)
                self.doubleSpinBox3[-1].setObjectName("doubleSpinBox3_"+crit)
                self.verticalLayout_3.addWidget(self.doubleSpinBox3[-1])
                self.doubleSpinBox3[-1].setValue(self.doubleSpinBox2[i].value())

            self.nb_column = self.nb_column + 1
            return 

    def reset(self):

        if(self.nb_column == 3 or self.nb_column == 4):
            for i, crit in enumerate(critList.items()):
                self.doubleSpinBox2[i].deleteLater() 
                
            self.doubleSpinBox2 = []
        
        if(self.nb_column == 4):
            for i, crit in enumerate(critList.items()): 
                self.doubleSpinBox3[i].deleteLater() 
                
            self.doubleSpinBox3 = []

        for i, (crit, (min, max)) in enumerate(critList.items()): 
                self.doubleSpinBox[i].setValue(min)

        self.nb_column = 2
        print("reset")
        return

    def next_page(self):
        value1 = []
        value2 = []
        value3 = []

        for i, crit in enumerate (critList.items()):
            value1.append(self.doubleSpinBox[i].value())
            if(self.nb_column == 3 or self.nb_column == 4):
                value2.append(self.doubleSpinBox2[i].value())
            if(self.nb_column == 4):
                value3.append(self.doubleSpinBox3[i].value())
        print(value1)
        print(value2)
        print(value3)


if __name__ == "__main__":
    import sys

    critList = {"crit1"   : (  0, 20),
                  "crit2"  : ( 10,  30),
                  "crit3"  : ( 20,  40),
                  "crit4"  : ( 30,  50),
                  "crit5"  : ( 40,  60),
                  "crit6"  : ( 50,  70),
                  "crit7"  : ( 10,  30),
                  "crit8"  : ( 20,  40),
                  "crit9"  : ( 30,  50),
                  "crit10"  : ( 40,  60),
                  "crit11"  : ( 50,  70)}    

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, critList)
    MainWindow.show()
    sys.exit(app.exec_())
